### ISSUE TITLE
Embark: conflict with embark-solc plugin

### ISSUE THREAD

**Issue by montyly** [crytic/crytic-compile#11]
If the [embark-solc](https://github.com/embark-framework/embark-solc) plugin is used, [embark-contract-info](https://github.com/crytic/embark-contract-info) will not work, because the [hook on compilation](https://github.com/crytic/embark-contract-info/blob/master/index.js#L58) will never be triggered. As a result, no json file is produced

**Comment by jrainville** [comment]
Hi @montyly , good catch. Thanks for reporting the issue. 

That's a bug in embark-solc. If you want, you can move the issue there.

Anyway, we'll publish a fix for that as soon as possible (should be this week)

**Comment by montyly** [comment]
Hi @jrainville, thank you for noticing the issue!

Let me know if I can help to fix the bug

**Comment by jrainville** [comment]
I just pushed a PR on embark-solc's repo (https://github.com/embark-framework/embark-solc/pull/29) . It should be merged and published soon.

**Comment by jrainville** [comment]
embark-solc v4.0.2 was just published fixing this problem: https://www.npmjs.com/package/embark-solc

**Comment by montyly** [comment]
`embark-solc` v4.0.2 works as expected! Thanks @jrainville!
