### ISSUE TITLE
Investigate standard-json for Solidity 0.8

### ISSUE THREAD

**Issue by montyly** [crytic/crytic-compile#140]
`solc` is about to drop `--combined-json` in profit of `standard-json`. This will break the integration of our tools.

We need to investigate how to use `standard-json`, and switch between `combined-json` and `standard-json` according to the solc version

Related: https://github.com/ethereum/solidity/issues/10278

**Comment by axic** [comment]
"standard-json" has been supported since 0.4.11, which means it is very likely that you only need to support standard json :wink:

**Comment by 0xalpharush** [comment]
https://github.com/crytic/crytic-compile/pull/29
