### ISSUE TITLE
Support solc 0.8

### ISSUE THREAD

**Issue by montyly** [crytic/crytic-compile#146]
https://docs.soliditylang.org/en/v0.8.0/080-breaking-changes.html#interface-changes
```
- The output of --combined-json has changed: JSON fields abi, devdoc, userdoc and storage-layout are sub-objects now. Before 0.8.0 they used to be serialised as strings.
- The “legacy AST” has been removed (--ast-json on the commandline interface and legacyAST for standard JSON). Use the “compact AST” (--ast-compact--json resp. AST) as replacement.
```

**Comment by axic** [comment]
I highly suggest to consider #140 to avoid supporting two versions of `--combined-json` which ultimately will be removed.

**Comment by montyly** [comment]
Thanks @axic for the tip. 

Unfortunately, we will need to keep both, as we want to keep support for 0.4.0 - 0.4.11 at least in the short term

**Comment by paulrberg** [comment]
Is solc v0.8 still not supported? I'm trying to run Echidna in a project and I'm getting this error:

> ERROR:CryticCompile:cache/solidity-files-cache.json not found

I don't know if this is caused by the lack of support for v0.8 or another issue with my configuration.

**Comment by montyly** [comment]
Hi @paulrberg . Solc 0.8 is supported (I forgot to close the issue with https://github.com/crytic/crytic-compile/pull/147)

This error looks like an hardhat issue, can you run `hardhat compile`? 
If you changed the default cache directory (in `hardhat.config.js`), you can use the flag `--hardhat-cache-directory new_dir` (or `cryticArgs: ["--hardhat-cache-directory", "new_dir"]` in Echidna's config file)

**Comment by paulrberg** [comment]
`npx hardhat compile` works. I didn't change the default cache directory, but [I did explicitly set it to `./cache`](https://github.com/paulrberg/solidity-template/blob/292d944429022ae525b34725891382670f3c9bd6/hardhat.config.ts#L76-L81).

Adding `cryticArgs: ["--hardhat-cache-directory", "cache"]` to the Echidna config file made it work, but if the cache folder is the same, this setting shouldn't be necessary.

**Comment by montyly** [comment]
This is indeed unexpected. I will investigate what happened on your branch. Thanks for sharing this

**Comment by paulrberg** [comment]
Thanks! Also good to know that after removing the explicit setting to `/cache`, running Echidna worked without passing the `--hardhat-cache-directory` argument.
