### ISSUE TITLE
Etherscan: compile with correct settings

### ISSUE THREAD

**Issue by montyly** [crytic/crytic-compile#151]
For example on https://etherscan.io/address/0x4c808e3c011514d5016536af11218eec537eb6f5#code

`crytic-compile` will not use `istanbul` and will fail the compilation
This is also true for the optimization settings

**Comment by SheldonHolmgren** [comment]
FWIW this is also true for remappings. Here is an example: https://optimistic.etherscan.io/address/0x8234f990b149ae59416dc260305e565e5dafeb54
