### ISSUE TITLE
Add Binance Smart Chain 

### ISSUE THREAD

**Issue by montyly** [crytic/crytic-compile#168]
We can add the bsc explorer to our etherscan support: https://bscscan.com/

**Comment by walkman941walkman941walkman941** [comment]
Hello

Thank you very much for your tools - they are very useful for me and i use them every day and i really need bsc support update for slither, and it is very critical for me to use this new functionality


I just need
Etherscan options:
  --etherscan-only-source-code
                        Only compile if the source code is available.
  --etherscan-only-bytecode
                        Only looks for bytecode.
  --etherscan-apikey ETHERSCAN_API_KEY
                        Etherscan API key.

but for bscscan

Really waiting for this update

Thank you

**Comment by walkman941walkman941walkman941** [comment]
hello

are there any updates for bsc support ? 

because bsc is growing very fast and bsc support for slither is very important

Thank you

**Comment by montyly** [comment]
This was done with https://github.com/crytic/crytic-compile/releases/tag/0.2.1
