### ISSUE TITLE
Add --node-modules-path flag

### ISSUE THREAD

**Issue by montyly** [crytic/crytic-compile#185]
For codebases with sub modules, crytic-compile is not able to find the dependencies properly. We should add a `--node-modules-path` or `--dependencies-path` flag allowing more flexibility.

An example is here: https://github.com/ethereum-optimism/optimism (and the current fix there was to do a `ln -s` on the directory https://github.com/ethereum-optimism/optimism/pull/848)

**Comment by 0xalpharush** [comment]
closed by https://github.com/crytic/crytic-compile/pull/324
