### ISSUE TITLE
Add support for truffle 5.3.14

### ISSUE THREAD

**Issue by montyly** [crytic/crytic-compile#199]
This https://github.com/trufflesuite/truffle/pull/4137 makes all our filenames wrong. We need to filter out `project://` from the metadata

**Comment by johnnylambada** [comment]
For grins I did this:

`for x in $(rg project: build -l); do sed -i "" -e 's,project:/,,g' $x; done` #rg is ripgrep

then

`slither --ignore-compile .`

And it seemed to work -- until I ran into the `custom error` problem ([#893](https://github.com/crytic/slither/issues/893))
