### ISSUE TITLE
feature request: foundry support

### ISSUE THREAD

**Issue by cruzdanilo** [crytic/crytic-compile#230]
![foundry](https://www.paradigm.xyz/static/Foundry_Ink_2-1024x516.jpg)

https://github.com/gakonst/foundry
https://www.paradigm.xyz/2021/12/introducing-the-foundry-ethereum-development-toolbox/

**Comment by montyly** [comment]
Hi @cruzdanilo. Thanks for pointing this, we will add the support for the next release.

I know that foundry is really recent platform, do you know projects using it to test our integration?

**Comment by gakonst** [comment]
FWIW the dir structure is the same as dapptools, so if you support dapptools there should be no work required!

**Comment by cruzdanilo** [comment]
@gakonst the output seems different, no `out/dapp.sol.json`. any workaround?

**Comment by gakonst** [comment]
Ah - you're right, my bad the output indeed is different.

The output dir structure is `FileName/Contract.json` with each json file having the `bin`, `abi` and `runtime-bin`

**Comment by gakonst** [comment]
Should be possible now that https://github.com/gakonst/foundry/issues/705 is merged
