### ISSUE TITLE
How to use crytic-compile for BSC?

### ISSUE THREAD

**Issue by botter-eng** [crytic/crytic-compile#239]
There are commands in the code, but can someone help me how to use the tool for the contracts on Binance Smart Chain? Thanks!

**Comment by 0xalpharush** [comment]
You can do the following:
```
crytic-compile bsc:[address]
```
(this requires the source code to be verified on bscscan.com)

**Comment by gaganborra** [comment]
Am getting 
"Unsupported platform." Error while executing it!

Command I have used : "crytic-compile bsc:0xbb4cdb9cbd36b01bd1cbaebf2de08d9173bc095c" (WBNB Contract address)

**Comment by 0xalpharush** [comment]
It works on the latest version, 0.2.2, of crytic-compile at the very least.
Can you check `crytic-compile --version` and upgrade to 0.2.2 if your version is not current?

**Comment by gaganborra** [comment]
0.2.2 bro! Just checked again!
