### ISSUE TITLE
ValueError: Unresolved target

### ISSUE THREAD

**Issue by Tanteli** [crytic/crytic-compile#243]
I executed the following steps: 

1. Install Echidna via Docker
2. Execute `echidna-test Vault.sol `

And received the error below

```
echidna-test: Couldn't compile given file
stdout:
stderr:
Traceback (most recent call last):
  File "/home/ethsec/.local/bin/crytic-compile", line 33, in <module>
    sys.exit(load_entry_point('crytic-compile==0.2.1', 'console_scripts', 'crytic-compile')())
  File "/home/ethsec/.local/lib/python3.6/site-packages/crytic_compile/__main__.py", line 194, in main
    compilations = compile_all(**vars(args))
  File "/home/ethsec/.local/lib/python3.6/site-packages/crytic_compile/crytic_compile.py", line 651, in compile_all
    raise ValueError(f"Unresolved target: {str(target)}")
ValueError: Unresolved target: Vault.sol
```
**Environment**:

node@v16.13.2
yarn@1.22.17
npm@8.1.2
echidna@1.7.2

**Comment by ggrieco-tob** [comment]
Hi, for crytic-compile issues, it is better to run directly the `crytic-compile Vault.sol` command. Can you check if it returns the same error?

**Comment by Tanteli** [comment]
> Hi, for crytic-compile issues, it is better to run directly the `crytic-compile Vault.sol` command. Can you check if it returns the same error?

Thanks for replying. I finally solved it. My file was not is the same directory.
