### ISSUE TITLE
solc_remap cannot find contract at remap path?

### ISSUE THREAD

**Issue by kevzettler** [crytic/crytic-compile#290]
cryptic-compile is failing to include an `@openzeppelin` contract that is installed in parent directory. I've tried to remap the path with `--solc-remaps` It consistently fails.
```
crytic-compile --hardhat-artifacts-directory ./build/contracts --solc-remaps '@openzeppelin/contracts/utils/Context.sol=../../node_modules/@openzeppelin/contracts/utils/Context.sol' .
INFO:CryticCompile:'npx hardhat compile --force' running
INFO:CryticCompile:Generating typings for: 50 artifacts in dir: ./build/typechain for target: ethers-v5
Successfully generated 150 typings!
Compiled 33 Solidity files successfully

ERROR:CryticCompile:(node:72314) ExperimentalWarning: stream/web is an experimental feature. This feature could change at any time
(Use `node --trace-warnings ...` to show where the warning was created)

ERROR:CryticCompile:Unknown file: @openzeppelin/contracts/utils/Context.sol
```

I can confirm that the `@openzeppelin` module is at that remap path

```
kevzettler@kevs-mbp-3 contracts % stat ../../node_modules/@openzeppelin/contracts/utils/Context.sol
16777232 61435240 -rw-r--r-- 1 kevzettler staff 0 844 "Sep 21 22:13:31 2022" "Sep 21 22:13:23 2022" "Sep 21 22:13:23 2022" "Sep 21 22:13:23 2022" 4096 8 0 ../../node_modules/@openzeppelin/contracts/utils/Context.sol
```

This project is a mono repo so the `node_modules` live in parent directory. I see there is some discussion about better monorepo support. Is this related to https://github.com/crytic/crytic-compile/issues/279 ? 

This project also uses a nonstandard hard hat artifact directory configured with `--hardhat-artifacts-directory` is that contributing to the problem?

**Comment by elopez** [comment]
Hi @kevzettler, thanks for the report! If you're using hardhat you don't need to specify remaps, hardhat will deal with that. Can you also reproduce the problem without passing solc-remaps?

**Comment by kevzettler** [comment]
hi @elopez yes if i remove remaps it still fails

```
kevzettler@kevs-mbp-3 contracts % crytic-compile --hardhat-artifacts-directory ./build/contracts .
INFO:CryticCompile:'npx hardhat compile --force' running
INFO:CryticCompile:Generating typings for: 50 artifacts in dir: ./build/typechain for target: ethers-v5
Successfully generated 150 typings!
Compiled 33 Solidity files successfully

ERROR:CryticCompile:(node:73911) ExperimentalWarning: stream/web is an experimental feature. This feature could change at any time
(Use `node --trace-warnings ...` to show where the warning was created)

ERROR:CryticCompile:Unknown file: @openzeppelin/contracts/utils/Context.sol
```

As I stated above
> This project is a mono repo so the node_modules live in parent directory. I see there is some discussion about better monorepo support. Is this related to https://github.com/crytic/crytic-compile/issues/279 ?

**Comment by 0xalpharush** [comment]
@kevzettler We made some changes to node module resolution. Let us know if it wasn't sufficient and we will reopen the issue.
