### ISSUE TITLE
Running Slither with Foundry Error 

### ISSUE THREAD

**Issue by PatoSF** [crytic/crytic-compile#291]
I'm getting an error while running slither in foundry. 

It is giving me **Access is Denied** 
Could not find the cache/solidity-files-cache.json file.

![Screenshot (18)](https://user-images.githubusercontent.com/64473943/191723942-9fc9e55c-dfee-4b91-b1bd-1ee446e759c7.png)

**Comment by elopez** [comment]
Hi @PatoSF! Thanks for the report. Could you please try the following two commands and confirm if they work correctly in that same folder? From the error message I suspect this might be an issue with foundry itself and/or permissions in your system (see the "Error: C:/..../out: access is denied" message early on).

`forge build --extra-output abi --extra-output userdoc --extra-output devdoc --extra-output evm.methodIdentifiers --force`

`crytic-compile .`

**Comment by PatoSF** [comment]
The two commands ran successfully ***@***.***

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows

**Comment by PatoSF** [comment]
@elopez  The two commands ran successfully.
![Screenshot (19)](https://user-images.githubusercontent.com/64473943/191750721-a997b72a-2666-4d4e-9050-aedf0801a278.png)

**Comment by PatoSF** [comment]
@elopez The first command ran successfully and the second throwed an error
![Screenshot (20)](https://user-images.githubusercontent.com/64473943/191751400-bef144a6-d8bd-46de-9acc-63d46e2df23d.png)

**Comment by elopez** [comment]
Interesting, can you confirm if the generated `out/` folder is readable and has json files in it?

Also, I see from your screenshot that the `cache` folder did not get generated when you ran foundry, can you confirm that you don't have `cache=true` set in `foundry.toml`?

**Comment by PatoSF** [comment]
@elopez I don't have cache = true in foundry.toml
After I ran forge build it gave me a cache.
When I ran crytic-compile it deleted the cache and idk why my windows antivirus keep popping out 
![Screenshot (22)](https://user-images.githubusercontent.com/64473943/191754770-08e6549c-412e-4e22-9b36-b2ec66099a39.png)

**Comment by PatoSF** [comment]
Output:

PS C:\Users\Pato SF\Desktop\foundther> crytic-compile .
INFO:CryticCompile:'forge build --extra-output abi --extra-output userdoc --extra-output devdoc --extra-output evm.methodIdentifiers --force' running
INFO:CryticCompile:
ERROR:CryticCompile:Error:
"C:/Users/Pato SF/Desktop/foundther/cache": **Access is denied**. (os error 5)

ERROR:CryticCompile:Could not find the cache/solidity-files-cache.json file.If you are using 'cache = true' in foundry's config file, please remove it. Otherwise please open an issue in https://github.com/crytic/crytic-compile

**Comment by elopez** [comment]
As far as I recall crytic-compile doesn't clean those folders, so it must be foundry deleting them and possibly failing to recreate them. I wonder if it could be the antivirus blocking the access (maybe it doesn't like something else running forge?) Could you test disabling the AV temporarily and seeing if the errors still persist?

**Comment by PatoSF** [comment]
After disabling my antivirus crytic-compile . ran successfully and gave the right output however I still have **access is denied**
 
![Screenshot (23)](https://user-images.githubusercontent.com/64473943/191907428-a0932c73-a93c-4fba-8fcd-d2b4c1e516d1.png)

**Comment by PatoSF** [comment]
@elopez Thank I fixed it. There were 2 solidity versions at the same time that why it wasn't working. 
Thank you for your help.
