### ISSUE TITLE
What is the whole command to run Slither on Windows PowerShell by Docker?

### ISSUE THREAD

**Issue by Alireza1994x** [crytic/crytic-compile#308]
I pulled Slither to my Windows 10 by Docker via this command:

`docker pull trailofbits/eth-security-toolbox`

This is a tool box that includes Slither too.

Now, I don't know what the whole and correct command is to run Slither and where I should try it!

But, What did I do? I did these steps:

1) I pushed PowerShell to the project directory to use Slither there.

2) I tried this command to run Slither in the next step:

`docker run -it trailofbits/eth-security-toolbox`

By this way, I entered to the tool box console and so I could use Slither there by trying Slither commands.

3) I tried Slither by:

`ethsec@d07cacedcb96:~$ slither contract.sol`

And this result emerged:

```
Traceback (most recent call last):
  File "/home/ethsec/.local/lib/python3.6/site-packages/slither/__main__.py", line 744, in main_impl
    ) = process_all(filename, args, detector_classes, printer_classes)
  File "/home/ethsec/.local/lib/python3.6/site-packages/slither/__main__.py", line 76, in process_all
    compilations = compile_all(target, **vars(args))
  File "/home/ethsec/.local/lib/python3.6/site-packages/crytic_compile/crytic_compile.py", line 660, in compile_all
    raise ValueError(f"Unresolved target: {str(target)}")
ValueError: Unresolved target: contract.sol
None
Error in contract.sol
Traceback (most recent call last):
  File "/home/ethsec/.local/lib/python3.6/site-packages/slither/__main__.py", line 744, in main_impl
    ) = process_all(filename, args, detector_classes, printer_classes)
  File "/home/ethsec/.local/lib/python3.6/site-packages/slither/__main__.py", line 76, in process_all
    compilations = compile_all(target, **vars(args))
  File "/home/ethsec/.local/lib/python3.6/site-packages/crytic_compile/crytic_compile.py", line 660, in compile_all
    raise ValueError(f"Unresolved target: {str(target)}")
ValueError: Unresolved target: contract.sol
```

4) So, I decided to try the another Slither command suggested in Slither [guide ](https://github.com/crytic/slither):

`ethsec@d07cacedcb96:~$ slither .`

But, This wasn't useful too and the same result emerged.

I don't know am I right or not? Is the work flow correct? Did I traverse the steps correctly? What did I miss in the work flow?

**Comment by elopez** [comment]
Hi @Alireza1994x! By default docker does not expose any files from your computer to the filesystem inside the container. If you would like to use files from your host computer inside the container, look into the [docker documentation for bind mounts](https://docs.docker.com/storage/bind-mounts/).

For instance, to expose your current directory as "/src" inside the container, you can run
```pwsh
docker run -it -v ${PWD}:/src trailofbits/eth-security-toolbox
```

Then once the container is running, you can move to `/src` and see your files, and run slither.
```sh
cd /src
ls
slither contract.sol
```

**Comment by Alireza1994x** [comment]
@elopez Thanks so much, Yes, It worked to me and the issue was eliminated!
