### ISSUE TITLE
Allow to compile a contract using public instead of external functions

### ISSUE THREAD

**Issue by ggrieco-tob** [crytic/crytic-compile#32]
The use of external functions can make property testing more difficult to use than expected, since the functions from a contract cannot be called from it (without using external call). It will be nice to have a flag in crytic-compile to replace the use of all `external` functions by `public` ones, without modifying the original source (this should work for complex projects like `truffle` to be really useful).

**Comment by ggrieco-tob** [comment]
Can we have this feature enabled with flag as well? It could be nice to use from Echidna just passing a flag to crytic-compile.

**Comment by montyly** [comment]
@ggrieco-tob: the feature is implemented in Slither. I don't think we should have crytic-compile calling slither, as it would create a dependency cycle.

Echidna should either call `slither-flat`, or have it linked to its documentation. 

I think it's important for Echidna to have good documentation around the UX of this tool:
- The file with the properties imports the file generate by `slither-flat`; if this is hidden from the user, all the third-party tools (IDE, linter) will report an error as the file will be inexistent on the first run. 
- If the project is updated, but `slither-flat` is not run, the properties will not run on the new version

We probably want to highlight that the user can run `slither-flat` separately, to bootstrap the flattening file, and then run echidna with a flag, so echidna will run `slither-flat` every time. Additionally `slither-flat` can be run by the user at any time if he changes the contracts' API and wants to have an up to date version when writing the properties.
