### ISSUE TITLE
Foundry _get_config_info fails if `cache_path` is used

### ISSUE THREAD

**Issue by elopez** [crytic/crytic-compile#326]
If `cache_path` is set to a non-default value in the foundry config, crytic-compile will not find `<cache_path>/solidity-files-cache.json`. We should probably detect where the cache path is, or add a custom option (like foundry_out_directory) to adjust the expected cache path.

---

If I do not comment the following line: https://github.com/theedisonlamp/crytic-issue/blob/main/foundry.toml#L4, `yarn slither` command results in:

```bash
yarn run v1.22.19
$ slither . --filter-paths "lib|test" --exclude naming-convention
'forge build --extra-output abi --extra-output userdoc --extra-output devdoc --extra-output evm.methodIdentifiers --force' running
Compiling 16 files with 0.8.16
(...)
crytic_compile.platform.exceptions.InvalidCompilation: Could not find the cache/solidity-files-cache.json file.If you are using 'cache = true' in foundry's config file, please remove it. Otherwise please open an issue in https://github.com/crytic/crytic-compile
```

_Originally posted by @theedisonlamp in https://github.com/crytic/slither/issues/1509#issuecomment-1355597979_

**Comment by 0xAurelou** [comment]
Don't know if it can Help but had this error when my project was not compiling, Once the project compile everything was working well for me.
Tested with ``slither . --filter-paths lib,test --exclude naming-convention``

**Comment by 0xalpharush** [comment]
This shouldn't be an issue any longer now that we are relying on build info instead of the cache https://github.com/crytic/crytic-compile/pull/348
