### ISSUE TITLE
ERROR:CryticCompile:Solidity version not found: 

### ISSUE THREAD

**Issue by KittyFu307** [crytic/crytic-compile#329]
When I try to use echidna-test to test my contract, it shows this error: 
echidna-test: Couldn't compile given file
stdout:
stderr:
ERROR:CryticCompile:Solidity version not found:

**Comment by 0xalpharush** [comment]
We will add a better error message

**Comment by 0xalpharush** [comment]
@KittyFu307 Would you try the latest release, `pip install crytic-compile==0.3.0`, and see if the error message is more helpful?  You likely need slither for echidna. so you could just upgrade it instead as it will include the latest release of crytic-compile, `pip install slither-analyzer==0.9.2`.
