### ISSUE TITLE
Publish latest version please

### ISSUE THREAD

**Issue by sambacha** [crytic/crytic-compile#330]
v0.2.4 is still the latest release that has been published, missing fixes for foundry. 

having to use workarounds like this:

```console
 pip3 install -U https://github.com/crytic/crytic-compile/archive/refs/heads/dev-fix-foundry-options.zip
```

_Originally posted by @elopez in https://github.com/crytic/slither/issues/1509#issuecomment-1355343953_

**Comment by Alexangelj** [comment]
+1

**Comment by theedisonlamp** [comment]
Following @elopez dev-fix installation, I configured a [preinstall script](https://github.com/crytic/slither/issues/1509#issuecomment-1355586189) to workaround this for the time being.

**Comment by montyly** [comment]
We will have a release this week

**Comment by 0xalpharush** [comment]
@sambacha We just released https://github.com/crytic/crytic-compile/releases/tag/0.3.0! Let us know if you run into any issues

**Comment by sambacha** [comment]
> @sambacha We just released https://github.com/crytic/crytic-compile/releases/tag/0.3.0! Let us know if you run into any issues

Hell yeah thanks for the heads up!
