### ISSUE TITLE
issue with file lookup in monorepo with nodemodules

### ISSUE THREAD

**Issue by 0xalpharush** [crytic/crytic-compile#367]
Reproduce
```
git clone https://github.com/code-423n4/2023-01-timeswap
yarn
cd v2-option
slither .
```
Error
```
File "/Users/alpharush/.pyenv/versions/3.10.0/envs/slither/lib/python3.10/site-packages/crytic_compile/crytic_compile.py", line 182, in filename_lookup
    raise ValueError(f"{filename} does not exist")
ValueError: /Users/alpharush/2023-01-timeswap/node_modules/@openzeppelin/contracts/token/ERC20/ERC20.sol does not exist
```

**Comment by bohendo** [comment]
Looks like the `node_module` finder in `crytic_compile/utils/naming.py` isn't being used by similar file-finding logic in `crytic_compile/compilation_unit.py`:

https://github.com/crytic/crytic-compile/blob/master/crytic_compile/compilation_unit.py#L216-L221

Gonna see if we can re-org our utils to share this logic a little better..
