### ISSUE TITLE
echidna-test: VM failed for unhandled reason, Query <EVM.Query: fetch contract 0x48BaCB9266a570d521063EF5dD96e61686DbE788>.

### ISSUE THREAD

**Issue by 0xKarl98** [crytic/crytic-compile#394]
This is the error message that i was trying to do fuzz testing using echidna 

Do you guys have any ideas on this ?

**Comment by ggrieco-tob** [comment]
Hi @0xKarl98, thanks for the report. Let's move this discussion to the [echidna bug tracker](https://github.com/crytic/echidna/issues). Also, please provide more details on how to reproduce this issue.

**Comment by 0xKarl98** [comment]
Thanks , i have provide details at the requsted place
