### ISSUE TITLE
`hardhat console` hangs when querying hardhat paths

### ISSUE THREAD

**Issue by nuliknol** [crytic/crytic-compile#416]
### Describe the issue:

When running  `~/bin/echidna . Whatever.sol` the command hags forever. The `.` is the Hardhat directory where a complete set of contracts is located.

### Code example to reproduce the issue:

I don't know how to reproduce it because I don't understand why it hangs

### Version:

2.1.1

### Relevant log output:

```shell
Apparently the process hangs forever because the hardhat command is invoked because it asks for `console` . I don't understand why a script asks for console, because there won't be any human interaction but this is what I am seeing , so probably there is a bug somewhere in launching hardhat. This is the output of `ps` command:

user       35342  0.0  0.0  17484  5204 pts/33   Ss   abr03   0:00              |   \_ bash
user      123630  0.0  0.3 1073791216 29692 pts/33 Sl+ 13:06   0:00              |   |   \_ /home/user/bin/echidna . BWTest.sol --config /home/user/eth/tests/echidna-bw.yaml --contract BWTest --test-mode property
user      123635  0.1  0.3  41408 26764 pts/33   S+   13:06   0:00              |   |       \_ /usr/bin/python3 /home/user/.local/bin/crytic-compile --solc-remaps @openzeppelin=/home/user/eth/dev/MyProject-Echidna/node_modules/@openzeppelin --solc-args=--optimize --solc-disable-warnings --export-format solc .
user      123688  0.3  0.7 708840 57232 pts/33   Sl+  13:06   0:01              |   |           \_ npm exec hardhat console --no-compile
user      123699  0.0  0.0   2892   956 pts/33   S+   13:06   0:00              |   |               \_ sh -c hardhat console --no-compile
user      123700  2.8  1.2 21959336 104812 pts/33 Sl+ 13:06   0:08              |   |                   \_ node /home/user/eth/dev/MyProject-Echidna/node_modules/.bin/hardhat console --no-compile
user      123711  2.5  1.2 11468392 98892 pts/33 Sl+  13:06   0:07              |   |                       \_ /usr/local/node-v16.15.0-linux-x64/bin/node --experimental-repl-await --require /home/user/eth/dev/MyProject-Echidna/node_modules/hardhat/register

So, the process 123711 makes the whole chain of processes wait forever because the 123711 process opens a console and since nobody types anything at the console all the parent processes enter "wait" state and nothing happens.
```

**Comment by elopez** [comment]
Thanks for helping triage this @nuliknol ! I've moved the issue to crytic-compile now. The extra `process.exit()` does not appear to cause any issues on my system, so that's probably something we can add to make it more compatible across different setups. Do you want to open a pull request with the change?

**Comment by nuliknol** [comment]
@elopez yeah, please add `process.exit()` if you can, I don't think pull request is needed, it is just a one line of code that needs to be changed

**Comment by elopez** [comment]
Alright, opened as #417 👍 (we use PRs to contribute new changes). If you can confirm the patched crytic-compile works correctly, that would be cool. You can install it with e.g. `pip install https://github.com/elopez/crytic-compile/archive/refs/heads/dev-fix-416.zip` (on a venv preferably, if you don't want to affect your current installation)

**Comment by nuliknol** [comment]
@elopez I have ran `crytic-compile` and it doesn't hang anymore, but I can't run the full test because `crytic-compile` doesn't find all the files (OpenZeppelin dependencies) in my hardhat directory. Maybe you could make a Release of echidna as binary and I could test it and see what happens?

**Comment by elopez** [comment]
echidna doesn't require any changes, crytic-compile is executed from your system's $PATH, so if you upgraded your installation it should be ok to test with your current echidna binary.

If you are referring to this error by the way: https://github.com/crytic/crytic-compile/issues/416#issuecomment-1499691025 , it looks like something odd is going on with your project. You may want to look into why `npx hardhat clean` throws that error. You can skip the cleaning step by adding `--skip-clean` to your echidna config's cryticArgs: `cryticArgs: ['--skip-clean']`

**Comment by nuliknol** [comment]
@elopez thanks! I don't have hanging problem anymore but I am getting a new error 

pkg_resources.ContextualVersionConflict: (crytic-compile 0.3.0 (/home/user/.local/lib/python3.10/site-packages), Requirement.parse('crytic-compile<0.4.0,>=0.3.1'), {'slither-analyzer'})

this is probably because I am using this new version of `crytic-compile` , anyway this issue can be closed now. thanks a lot!
