### ISSUE TITLE
Failed to find foundry.toml in CI environment when target is not root dir

### ISSUE THREAD

**Issue by LEAFERx** [crytic/crytic-compile#509]
## Describe the problem

Currently when using `crytic/slither-action@0.3.0`, slither failed to run `forge clean`, complaining `FileNotFoundError: [Errno 2] No such file or directory: 'foundry.toml'` (see https://github.com/SpecularL2/specular/actions/runs/6577194479/job/17868312892#step:9:321).

However, just before this, slither is able to install foundry dependencies using `foundry.toml` (see https://github.com/SpecularL2/specular/actions/runs/6577194479/job/17868312892#step:9:317) and we have confirmed that `foundry.toml` is inside the directory (see https://github.com/SpecularL2/specular/actions/runs/6577194479/job/17868312892#step:8:19).

We confirmed this problem in both slither `v0.9.6` and `v0.10.0`. This problem did not happen before yesterday (when sliter `v0.10.0` and crytic-compile `v0.3.5` released). We suspect this is a problem related to `crytic-compile` foundry changes in `v0.3.5` release.

We suspect that this is caused by the `target` is not root directory, which is common in monorepo. We confirmed in a minimal reproducible example that things work smoothly when `target` is the root directory.

## How to reproduce

We created a minimal reproducible example [here](https://github.com/LEAFERx/slither-mre) with the failed action [here](https://github.com/LEAFERx/slither-mre/actions/runs/6577537750/job/17869396171). This example is created by calling `forge init` under `contracts` folder and adding slither action.

**Comment by michaelkaplan13** [comment]
Also hitting this same issue.

**Comment by 0xalpharush** [comment]
fixed by https://github.com/crytic/crytic-compile/pull/515
