### ISSUE TITLE
CryticCompile out/build-info is not a directory

### ISSUE THREAD

**Issue by metatrust-v** [crytic/crytic-compile#513]
repo:
https://github.com/open-dollar/od-contracts/

INFO:CryticCompile:'forge clean' running (wd: /opt/local/projects)
INFO:CryticCompile:'forge build --build-info' running (wd: /opt/local/projects)
ERROR:CryticCompile:Compilation failed. Can you run build command?
out/build-info is not a directory.

**Comment by elopez** [comment]
Hi @metatrust-v, thanks for the report! Can you confirm if `/opt/local/projects` is your copy of od-contracts? You might have misspecified the target directory in the command if it is not.

If that's correct, can you confirm if `forge build --build-info` works correctly from that directory? I tried compiling it locally but it did not work:

```shell
cd /opt/local/projects && forge build --build-info
```

Here's the error I received:

```shell
$ forge build --build-info
[⠔] Compiling...
[⠃] Compiling 171 files with 0.8.19
[⠒] Solc 0.8.19 finished in 3.51s
Error: 
Compiler run failed:
Error (7576): Undeclared identifier.
   --> script/Deploy.s.sol:278:24:
    |
278 |     protocolToken.mint(CASSY, AIRDROP_AMOUNT / 3);
    |                        ^^^^^

```



Lastly, can you try upgrading your crytic-compile to the latest release and trying again? The latest crytic-compile skips scripts and tests on forge projects so you might have a bit more of success with it.

**Comment by metatrust-v** [comment]
Thank you very much for your help. @elopez
